# This is an OpenAPI Specification (https://swagger.io/specification/)
# for the ERS API
# owned by NHS Digital (https://digital.nhs.uk/)
openapi: "3.0.0"

info:
  version: "0.0.1"
  title: Electronic Referral Api
  description: |
    ## Overview
    Use this API for any actions regarding referrals.

    ## Endpoints
    To see details for specific endpoints, select from the list on the left hand side of the page:
    - `GET /ers-api`
  contact:
    name: API Management Support
    email: api.management@nhs.net

servers:
  - url: 'https://internal-dev.api.service.nhs.uk/ers-api'
    description: Internal-Dev environment.

paths:

  /ers-api:
    get:
      summary: Retrieve a referral request and return a status code of 200 and referral request upon succession.
      operationId: retrieveDataFromERS
      description: |
        Get a 200 response from an user restricted endpoint.

      responses:
        '200':
          description: Successful response.
          content:
            application/json:
              schema:
                type: object
                properties:
                  referralObject:
                    type: object
                    example: "{}"
      tags:
        - ers
components:

  securitySchemes:
    oAuth2AuthCode:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://sandbox.api.service.nhs.uk/oauth2/authorize
          tokenUrl: https://sandbox.api.service.nhs.uk/oauth2/token
          scopes: {}
  schemas:
    Greeting:
      $ref: components/schemas/Greeting.yaml

tags:
  - name: ers
